No need to tap homebrew/bundle anymore.
```
Error: homebrew/bundle was deprecated. This tap is now empty and all its
contents were either deleted or migrated.
```